[package]
name = "cs453-pap-server"
description = "CS453 Program Analysis Platform Server"
version = "0.1.0"
authors = ["Meng Xu <meng.xu.cs@uwaterloo.ca>"]
license = "GPL-3.0"
edition = "2021"

[dependencies]
# http
tiny_http = "*"
# filesystem
zip = "*"
tempdir = "*"
# auth
ssh-key = { version = "*", features = ["ed25519"] }
# logging
log = "*"
stderrlog = "*"
# utilities
anyhow = "*"
once_cell = "*"
# worker
cs453-pap-worker = { path = "../worker" }